version: '3.8'

services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.debug
    command: python manage.py check
    environment:
      DJANGO_SECRET_KEY: test-key
      DJANGO_DEBUG: "True"
      DJANGO_ALLOWED_HOSTS: "*"