# Generated by Django 4.2.20 on 2025-05-06 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=120, verbose_name='Razão Social')),
                ('nome_fantasia', models.CharField(blank=True, max_length=120, null=True, verbose_name='Nome Fantasia')),
                ('cnpj', models.CharField(max_length=14, unique=True, verbose_name='CNPJ')),
                ('ie', models.CharField(blank=True, max_length=20, null=True, verbose_name='Inscrição Estadual')),
                ('rntrc', models.CharField(blank=True, max_length=8, null=True, verbose_name='RNTRC')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('telefone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone')),
                ('cep', models.CharField(blank=True, max_length=8, null=True, verbose_name='CEP')),
                ('logradouro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Logradouro')),
                ('numero', models.CharField(blank=True, max_length=10, null=True, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=60, null=True, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, max_length=60, null=True, verbose_name='Bairro')),
                ('municipio', models.CharField(blank=True, max_length=60, null=True, verbose_name='Município')),
                ('uf', models.CharField(blank=True, max_length=2, null=True, verbose_name='UF')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logotipo')),
                ('certificado_digital', models.CharField(blank=True, max_length=255, null=True, verbose_name='Certificado A1 (Nome)')),
                ('responsavel_tecnico_cnpj', models.CharField(blank=True, max_length=14, null=True, verbose_name='CNPJ Responsável Técnico')),
                ('responsavel_tecnico_contato', models.CharField(blank=True, max_length=60, null=True, verbose_name='Nome Responsável Técnico')),
                ('responsavel_tecnico_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Responsável Técnico')),
                ('responsavel_tecnico_fone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone Responsável Técnico')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração da Empresa',
                'verbose_name_plural': 'Configuração da Empresa',
            },
        ),
        migrations.CreateModel(
            name='ParametroSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome do Parâmetro')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('valor', models.CharField(max_length=255, verbose_name='Valor')),
                ('grupo', models.CharField(choices=[('GERAL', 'Configurações Gerais'), ('ALERTA', 'Configurações de Alertas'), ('PAGTO', 'Configurações de Pagamentos'), ('EMAIL', 'Configurações de Email'), ('BACKUP', 'Configurações de Backup')], default='GERAL', max_length=10, verbose_name='Grupo')),
                ('tipo_dado', models.CharField(choices=[('int', 'Inteiro'), ('float', 'Decimal'), ('str', 'Texto'), ('bool', 'Booleano'), ('date', 'Data'), ('json', 'JSON')], default='str', max_length=20, verbose_name='Tipo de Dado')),
                ('editavel', models.BooleanField(default=True, verbose_name='Editável')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Parâmetro do Sistema',
                'verbose_name_plural': 'Parâmetros do Sistema',
                'ordering': ['grupo', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='RegistroBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('nome_arquivo', models.CharField(max_length=100, verbose_name='Nome do Arquivo')),
                ('tamanho_bytes', models.PositiveBigIntegerField(verbose_name='Tamanho (bytes)')),
                ('md5_hash', models.CharField(max_length=32, verbose_name='Hash MD5')),
                ('localizacao', models.CharField(max_length=255, verbose_name='Localização')),
                ('usuario', models.CharField(max_length=150, verbose_name='Usuário')),
                ('status', models.CharField(choices=[('completo', 'Completo'), ('parcial', 'Parcial'), ('erro', 'Erro')], default='completo', max_length=20, verbose_name='Status')),
                ('detalhes', models.TextField(blank=True, null=True, verbose_name='Detalhes')),
            ],
            options={
                'verbose_name': 'Registro de Backup',
                'verbose_name_plural': 'Registros de Backup',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.AlterModelOptions(
            name='cteprotocoloautorizacao',
            options={'verbose_name': 'CT-e – Protocolo'},
        ),
        migrations.AddField(
            model_name='mdfedocumento',
            name='data_encerramento',
            field=models.DateField(blank=True, null=True, verbose_name='Data Encerramento'),
        ),
        migrations.AddField(
            model_name='mdfedocumento',
            name='encerrado',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Encerrado'),
        ),
        migrations.AddField(
            model_name='mdfedocumento',
            name='municipio_encerramento_cod',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Código Município Encerramento'),
        ),
        migrations.AddField(
            model_name='mdfedocumento',
            name='protocolo_encerramento',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Protocolo Encerramento'),
        ),
        migrations.AddField(
            model_name='mdfedocumento',
            name='uf_encerramento',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='UF Encerramento'),
        ),
        migrations.CreateModel(
            name='MDFeCancelamentoEncerramento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_evento', models.CharField(max_length=54, unique=True, verbose_name='ID Evento')),
                ('c_orgao', models.CharField(max_length=2, verbose_name='Código Órgão IBGE')),
                ('tp_amb', models.PositiveSmallIntegerField(verbose_name='Tipo Ambiente')),
                ('cnpj', models.CharField(max_length=14, verbose_name='CNPJ Solicitante')),
                ('cpf', models.CharField(blank=True, max_length=11, null=True, verbose_name='CPF Solicitante')),
                ('dh_evento', models.DateTimeField(verbose_name='Data/Hora Evento')),
                ('tp_evento', models.CharField(default='110113', max_length=6, verbose_name='Tipo Evento')),
                ('n_seq_evento', models.PositiveSmallIntegerField(default=1, verbose_name='Sequência Evento')),
                ('versao_evento', models.CharField(default='3.00', max_length=5, verbose_name='Versão Evento')),
                ('n_prot_cancelar', models.CharField(max_length=15, verbose_name='Protocolo Encerramento a Cancelar')),
                ('x_just', models.TextField(verbose_name='Justificativa')),
                ('id_retorno', models.CharField(blank=True, max_length=15, null=True, verbose_name='ID Retorno')),
                ('ver_aplic', models.CharField(blank=True, max_length=20, null=True, verbose_name='Versão Aplicação Resposta')),
                ('c_stat', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Código Status Resposta')),
                ('x_motivo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Motivo Status Resposta')),
                ('dh_reg_evento', models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora Registro Evento')),
                ('n_prot_retorno', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Protocolo Evento')),
                ('arquivo_xml_evento', models.FileField(blank=True, null=True, upload_to='xml_eventos_mdfe/', verbose_name='XML Evento Canc. Encerramento')),
                ('mdfe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cancelamento_encerramento', to='transport.mdfedocumento')),
            ],
            options={
                'verbose_name': 'MDF-e – Cancelamento de Encerramento',
                'verbose_name_plural': 'MDF-e – Cancelamentos de Encerramento',
                'db_table': 'mdfe_cancelamento_encerramento',
            },
        ),
    ]
